backend:
  name: git-gateway
  branch: master
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Keywords", name: "metaKeywords", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Thumbnail", name: "thumb", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
